# Generated by Django 4.2.8 on 2023-12-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=25)),
                ("apellido", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("celular", models.IntegerField(max_length=9)),
                ("fecha_nacimiento", models.DateField()),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
