# Generated by Django 4.1.1 on 2023-12-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "perezdearceApp",
            "0004_remove_usuarios_is_active_remove_usuarios_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="celular",
            field=models.IntegerField(),
        ),
    ]
